const menu = [
  {
    id: 1,
    title: 'Maślane pancakes',
    category: 'śniadanie',
    price: 19.99,
    img: '/images/item-1.jpeg',
    desc: `Naleśniki w stylu amerykańskim, podawane z syropem klonowym i sezonowymi owocami. Na życzenie serwujemy dodatkową bitą śmietanę.`,
  },
  {
    id: 2,
    title: 'smak double',
    category: 'obiad',
    price: 34.99,
    img: '/images/item-2.jpeg',
    desc: `Uczta dla miłośników smaku i apetytu. Podwójna wołowina, ser cheddar, świeże warzywa i sos Yummm, podane w chrupiącej bułce.`,
  },
  {
    id: 3,
    title: 'milkshake godzilla',
    category: 'shake',
    price: 15.99,
    img: '/images/item-3.jpeg',
    desc: `Bomba smakowa dla fanów słodkości. Owocowy milkshake, serwowany z donutem, bitą śmietaną, owocami i kolorową posypką.`,
  },
  {
    id: 4,
    title: 'Wiejska rozkosz',
    category: 'śniadanie',
    price: 18.99,
    img: '/images/item-4.jpeg',
    desc: `Oto prawdziwa ucieczka od miejskiego zgiełku. Dwa sadzone jajka, fasola, ser cheddar i tosty, a do tego pyszna kawa, taka jak lubisz.`,
  },
  {
    id: 5,
    title: 'Jajeczny król',
    category: 'obiad',
    price: 29.99,
    img: '/images/item-5.jpeg',
    desc: `Soczysty burger wołowy z warzywami i z jajkiem sadzonym, którego żółtko rozpływa się w ustach i po pozostałych składnikach.`,
  },
  {
    id: 6,
    title: 'pora na oreo',
    category: 'shake',
    price: 15.99,
    img: '/images/item-6.jpeg',
    desc: `Mleko, lody waniliowe i ciasteczka oreo w kompozycji idealnej, polecają się na umilenie każdej pory dnia i roku. Zdołasz się oprzeć?`,
  },
  {
    id: 7,
    title: 'beko-nowy dzień',
    category: 'śniadanie',
    price: 18.99,
    img: '/images/item-7.jpeg',
    desc: `Śniadaniowy burger z jajeczną bułeczką, z dużą ilością chrupiacego, aromatycznego bekonu na dobry początek dnia.`,
  },
  {
    id: 8,
    title: 'amerykański klasyk',
    category: 'obiad',
    price: 30.99,
    img: '/images/item-8.jpeg',
    desc: `Dla tradycjonalistów klasyczny burger - pojedynczy kotlet wołowy, boczek, ser cheddar, warzywa i majonez. Serwowany z frutkami. `,
  },
  {
    id: 9,
    title: 'Shake Break',
    category: 'shake',
    price: 16.99,
    img: '/images/item-9.jpeg',
    desc: `Przerwa na shake'a. Kadego dnia inny smak w ofercie. Najlepiej smakuje z druga osobą - drugiego shake'a dostaniecie za pół ceny. `,
  },
]
export default menu
